### PR TITLE
Add Evil Martians open source

### PR DESCRIPTION
**Pull request by ai**
I added open source projects from my collegues

### CODE REVIEW

**Comment by ai** [comment]
Oh. Await a second, because of the wrong rebase I removed some recent changes.

**Comment by ai** [comment]
@igoradamenko fixed

**Comment by igoradamenko** [comment]
Thanks!

**Comment by ai** [comment]
@igoradamenko oops. My links are showing without a newline before description. What trick do you use to put a newline?

**Comment by igoradamenko** [comment]
I've already fixed them.

I use two spaces in the end of the first line of each item. It's a common Markdown way to add `\n` 🐨

**Comment by igoradamenko** [comment]
I've replaced them with `<br>` to make the idea more explicit for contributors: https://github.com/igoradamenko/awesome-made-by-russians/commit/c69aa9ad5b25569ddbb8b60415ccb51ae1a4ee3c

Should be clearer now.

**Pull request merged**
