### PR TITLE
Add JSS

### PR DESCRIPTION
**Pull request by ai**
@kof sorry, I am not sure that you are from Russia. Are you OK with adding your project to this list?

### CODE REVIEW

**Comment by kof** [comment]
I am not against adding it to this list, though I have serious concerns around the name of this list.
What does it mean 'by russians'? Born in Russia? Has a Russian citizenship? Speaks Russian? Russian ethnicity? What about Belarus, Ukrain etc ... considered russian? 

How many people will be offended in particular because of what happened in the Ukrain?

To make the problem more clear, here is my background:
I was born in Russia, lived in Belarus since till I was 17, then moved to Germany. I have 2 citizenships. I speak Russian natively along with German.

**Comment by kof** [comment]
I don't know how to fix this, just by explaining better what is meant in the description (not sure this can be good enough at all) or change a name to something that expresses the intent more clearly.

**Comment by ai** [comment]
> What does it mean 'by russians'?

Yeap. We prediecrted this question and put this note to docs: “The project was created by the developer born in Russia or self-indicate themself as a part of Russian ethnicity.”

**Comment by ai** [comment]
Also in docs, we mentioned the reasons behind this list:

> The goal of the project is to highlight how modern IT is a product of global culture. There are many different nations in your package-lock.json, or Gemfile.lock, or elsewhere. And we are highlighting the Russian part just because we know it better.

So it is more about showing that software is not written just in USA, rather than saying something specific about Russia.

**Comment by igoradamenko** [comment]
> What about Belarus, Ukrain etc ... considered russian?

It's not like we're trying to “claim every Russian speaking people as Russian”. It depends on the author of the software. If the author self-indicate themself as a Russian, well, their software is “made by Russian”.

> How many people will be offended in particular because of what happened in the Ukraine? 

I don't this that this is a right place to discuss Ukraine/Russia relationship. The repo is not about that overall.

----

@kof, I understand what you mean, but at the same time I believe that it's completely depends on the vector of thought and on the point of view. We were trying to describe it well in #2.

If you think that it's not right to describe your project is “made by Russian”, feel free to say “No”, it's totally alright and understandable.

**Comment by kof** [comment]
I have a feeling this won't be sufficient

**Comment by kof** [comment]
Like I said I personally don't have a problem with that.

**Comment by igoradamenko** [comment]
Okay, thanks!

@ai, I've added JSS in https://github.com/igoradamenko/awesome-made-by-russians/commit/22468a1c24dd6e646c1fe69db70000fbf8644444.

**Pull request closed without merging**
