### PR TITLE
Add PHP Parser

### PR DESCRIPTION
**Pull request by win0err**
Add PHP Parser by Nikita Popov

### CODE REVIEW

**Comment by igoradamenko** [comment]
Hey!

I don't want to mess something up, so do you have any proof that Nikita Popov is Russian?

I've heard an episode of SDCast with him as a guest, and it looked like he had an accent, and he said that he translated PHP docs from German to English and vice versa, which may indicate that may be he doesn't Russian.

https://poddtoppen.se/podcast/890468606/sdcast/sdcast-103-v-gostyax-nikita-popov

AFAIK, Nikita also created https://github.com/nikic/FastRoute, and it would be great to add it too. But we have to be sure that he's Russian, to prevent any misunderstanding or offending.

**Comment by win0err** [comment]
Ok. I'll ask @nikic about this

**Comment by nikic** [comment]
Depends on what counts as Russian ;) I was born in Russia, but I live in Germany & have German citizenship.

**Comment by win0err** [comment]
> Depends on what counts as Russian ;) I was born in Russia, but I live in Germany & have German citizenship.

README says: 
> The project was created by the developer born in Russia or self-indicate themself as Russian.

**Comment by igoradamenko** [comment]
Well, if @nikic is not against adding his projects into the list, then why not!

Thank you guys for your contribution and time!

**Pull request merged**
