### PR TITLE
Adding tacit - user-friendly CSS framework

### PR DESCRIPTION
**Pull request by akuleshov7**
### What is tacit:
Tacit is a primitive CSS framework for dummies, like myself, who don't know anything about graphic design but want their web services to look eatable. No classes, no layouts. Just design plain and simple web pages compliant with HTML5 and they will look OK.

### About author:
Yegor - is russian open-source enthusiast, proactive github contributor.

### CODE REVIEW

**Comment by igoradamenko** [comment]
Hi, Andrey!

Thanks for the contribution, but are you sure that Yegor is a Russian? We had the same discussion some months ago, and it looked like he's not: #64.

I don't want to accidentally offend him in any ways, so we have to be completely sure 🐨

**Comment by akuleshov7** [comment]
> Hi, Andrey!
> 
> Thanks for the contribution, but are you sure that Yegor is a Russian? We had the same discussion some months ago, and it looked like he's not: #64.
> 
> I don't want to accidentally offend him in any ways, so we have to be completely sure 🐨

Have seen him a week ago in Moscow, where he lives, on meetup

**Comment by akuleshov7** [comment]
As I know he works at Huawei in Moscow right now. He is a lab director there.

**Comment by yegor256** [comment]
@igoradamenko I'm definitely Russian, but thanks for double-checking :)

**Comment by igoradamenko** [comment]
Thank you all guys! 🚀

**Pull request merged**
