### PR TITLE
Add SVGO

### PR DESCRIPTION
**Pull request by lahmatiy**

### CODE REVIEW

**Comment by igoradamenko** [comment]
Hmm. Are you sure?

https://github.com/svg/svgo/blob/master/LICENSE

> Copyright © 2012–2016 Kir Belevich

**Comment by lahmatiy** [comment]
Yeah, looks odd. Kir is the author. However, he didn't contribute to it for a long time and Lev is the current active maintainer for several years https://github.com/svg/svgo/graphs/contributors

**Comment by lahmatiy** [comment]
It depends how to choose a person – is it an author or current maintainer/contributor. According to the tweet you cited `open source project mainly contributed by` looks like it mostly about most valuable maintainer/contributor rather than initial author. Isn't it?

**Comment by igoradamenko** [comment]
Until now I tried to stick the way of adding only the projects that were made by Russians:

> If you want to add project to this list, please, make sure that:
> 1. The project was created by the developer born in Russia or self-indicate themself as Russian.

The reason is simple — a project is created only once, while main contributor may be different every month.

It's a bit unfair with cases like this one, but it's easier to resolve disputes when you have a simple rule.

**Comment by igoradamenko** [comment]
Oh, not sure what to do.

On the one hand, the author's name is important. On the other hand, Lev is maintained the project since 2013-2014.

I guess it would be fair to merge the PR but mark Lev as “main contributor”, just to distinct him from the original author of the repo.

**Comment by igoradamenko** [comment]
Done: https://github.com/igoradamenko/awesome-made-by-russians/commit/aab52574e7be0c5883a43d2cd230b4f5a18120f8

Thanks for the PR! 👍

**Pull request merged**
