### PR TITLE
Add Victoria Metrics

### PR DESCRIPTION
**Pull request by chebyrash**

### CODE REVIEW

**Comment by igoradamenko** [comment]
Wait, but the author of the project is from Kyiv: https://github.com/valyala.

**Comment by igoradamenko** [comment]
Actually, avva is from Ukraine too.

I think we should remove Memcached from the list. It's a bit controversial to add it there. Plus it was firstly written by Brad Fitzpatrick:

https://en.wikipedia.org/wiki/Memcached

**Comment by chebyrash** [comment]
You did say authors could be
> or post USSR programmers
from post USSR countries?

**Comment by igoradamenko** [comment]
Hm. You're right. I probably should remove this from the README. 

Sometimes “Russian” may hurt people feelings, esp. when we call Ukrainians or Belarus people so. Even though we don't want to offend them (e.g. #6). That's why we added this line:

> The project was created by the developer born in Russia or self-indicate themself as a part of Russian ethnicity.

So, I can't be 100% sure that these guys from Ukraine call themselves Russian (even though their projects are awesome), and I definitely don't want to offend anybody.

----

Anyway, thank you for your contribution. I will remove the “post USSR” part from the README!

**Pull request closed without merging**
